name: Java CI/CD with Docker and EC2

on:
  push:
    branches: [ "main" ] # main 브랜치에 push되면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. 자바 설정 및 Gradle 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 제외 빌드 (필요시 수정)

      # 3. 도커 로그인 및 이미지 빌드/푸시
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stage-log .
          docker push ${{ secrets.DOCKER_USERNAME }}/stage-log

      # 4. EC2에 접속하여 배포 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존에 돌아가던 컨테이너 중지 및 삭제
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            # 최신 이미지 pull 받기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/stage-log
            # 새 컨테이너 실행
            sudo docker run -d --name my-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/stage-log